=== Mr-Monster-0248/noMayhemTravel/public/country/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "university",
    "link_website",
    "country",
    "admission",
    "prices",
    "hints",
    "comments"
  ],
  "properties": {
    "university": {
      "$id": "#/properties/university",
      "type": "string",
      "title": "The University Schema",
      "default": "",
      "examples": [
        "Concordia University"
      ],
      "pattern": "^(.*)$"
    },
    "link_website": {
      "$id": "#/properties/link_website",
      "type": "string",
      "title": "The Link_website Schema",
      "default": "",
      "examples": [
        "https://www.concordia.ca/"
      ],
      "pattern": "^(.*)$"
    },
    "country": {
      "$id": "#/properties/country",
      "type": "object",
      "title": "The Country Schema",
      "required": [
        "name",
        "flag_url",
        "currency"
      ],
      "properties": {
        "name": {
          "$id": "#/properties/country/properties/name",
          "type": "string",
          "title": "The Name Schema",
          "default": "",
          "examples": [
            "Canada"
          ],
          "pattern": "^(.*)$"
        },
        "flag_url": {
          "$id": "#/properties/country/properties/flag_url",
          "type": "string",
          "title": "The Flag_url Schema",
          "default": "",
          "examples": [
            "ðŸ‡¨ðŸ‡¦"
          ],
          "pattern": "^(.*)$"
        },
        "currency": {
          "$id": "#/properties/country/properties/currency",
          "type": "string",
          "title": "The Currency Schema",
          "default": "",
          "examples": [
            "Dollar canadien -> 1 â‚¬ = 1.51 $"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "admission": {
      "$id": "#/properties/admission",
      "type": "object",
      "title": "The Admission Schema",
      "required": [
        "gpa",
        "mark",
        "toeic"
      ],
      "properties": {
        "gpa": {
          "$id": "#/properties/admission/properties/gpa",
          "type": "object",
          "title": "The Gpa Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/admission/properties/gpa/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "2.8"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/admission/properties/gpa/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "3.9"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/admission/properties/gpa/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "3.5"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        "mark": {
          "$id": "#/properties/admission/properties/mark",
          "type": "object",
          "title": "The Mark Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/admission/properties/mark/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "13.5"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/admission/properties/mark/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "15.9"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/admission/properties/mark/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "14.7"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        "toeic": {
          "$id": "#/properties/admission/properties/toeic",
          "type": "object",
          "title": "The Toeic Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/admission/properties/toeic/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "630"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/admission/properties/toeic/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "975"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/admission/properties/toeic/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "750"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    },
    "prices": {
      "$id": "#/properties/prices",
      "type": "object",
      "title": "The Prices Schema",
      "required": [
        "plane",
        "food",
        "rent",
        "trains and bus",
        "transport",
        "extras"
      ],
      "properties": {
        "plane": {
          "$id": "#/properties/prices/properties/plane",
          "type": "object",
          "title": "The Plane Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/prices/properties/plane/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "250"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/prices/properties/plane/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "500"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/prices/properties/plane/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "375"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        "food": {
          "$id": "#/properties/prices/properties/food",
          "type": "object",
          "title": "The Food Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/prices/properties/food/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "100"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/prices/properties/food/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "300"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/prices/properties/food/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "200"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        "rent": {
          "$id": "#/properties/prices/properties/rent",
          "type": "object",
          "title": "The Rent Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/prices/properties/rent/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "500"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/prices/properties/rent/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "2500"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/prices/properties/rent/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "1000"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        "trains and bus": {
          "$id": "#/properties/prices/properties/trains and bus",
          "type": "object",
          "title": "The Trains and bus Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/prices/properties/trains and bus/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "30"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/prices/properties/trains and bus/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "100"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/prices/properties/trains and bus/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "65"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        "transport": {
          "$id": "#/properties/prices/properties/transport",
          "type": "object",
          "title": "The Transport Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/prices/properties/transport/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "30"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/prices/properties/transport/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "100"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/prices/properties/transport/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "65"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        "extras": {
          "$id": "#/properties/prices/properties/extras",
          "type": "object",
          "title": "The Extras Schema",
          "required": [
            "min",
            "max",
            "average"
          ],
          "properties": {
            "min": {
              "$id": "#/properties/prices/properties/extras/properties/min",
              "type": "string",
              "title": "The Min Schema",
              "default": "",
              "examples": [
                "50"
              ],
              "pattern": "^(.*)$"
            },
            "max": {
              "$id": "#/properties/prices/properties/extras/properties/max",
              "type": "string",
              "title": "The Max Schema",
              "default": "",
              "examples": [
                "700"
              ],
              "pattern": "^(.*)$"
            },
            "average": {
              "$id": "#/properties/prices/properties/extras/properties/average",
              "type": "string",
              "title": "The Average Schema",
              "default": "",
              "examples": [
                "355"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    },
    "hints": {
      "$id": "#/properties/hints",
      "type": "array",
      "title": "The Hints Schema",
      "items": {
        "$id": "#/properties/hints/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "text"
        ],
        "properties": {
          "text": {
            "$id": "#/properties/hints/items/properties/text",
            "type": "string",
            "title": "The Text Schema",
            "default": "",
            "examples": [
              "Traverser le troittoir au feu rouge est passible de 50 euros d'ammende"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "comments": {
      "$id": "#/properties/comments",
      "type": "array",
      "title": "The Comments Schema",
      "items": {
        "$id": "#/properties/comments/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "text"
        ],
        "properties": {
          "text": {
            "$id": "#/properties/comments/items/properties/text",
            "type": "string",
            "title": "The Text Schema",
            "default": "",
            "examples": [
              "Attention le sixiÃ¨me semestre en France sera rude car on repasse sur des horraires de 8h Ã  18h."
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    }
  }
}

=== Mr-Monster-0248/noMayhemTravel/public/country/staffordshire.json
{
  "university": "Straffordshire University",
  "link_website": "http://www.staffs.ac.uk/",
  "country": {
    "name": "England",
    "flag_url": "\uD83C\uDDEC\uD83C\uDDE7",
    "currency": "Livre Sterling -> 1 € = 0.89 £"
  },
  "admission": {
    "gpa": {
      "min": "0.4",
      "max": "1.5",
      "average": "1"
    },
    "mark": {
      "min": "11",
      "max": "16.08",
      "average": "13"
    },
    "toeic": {
      "min": "600",
      "max": "850",
      "average": "725"
    }
  },
  "prices": {
    "total_price": {
      "min": "4150",
      "max": "8200",
      "average": "7850"
    },
    "plane": {
      "min": "400",
      "max": "600",
      "average": "500"
    },
    "food": {
      "min": "150",
      "max": "300",
      "average": "220"
    },
    "rent": {
      "min": "300",
      "max": "500",
      "average": "400"
    },
    "trains and bus": {
      "min": "50",
      "max": "200",
      "average": "125"
    },
    "transport": {
      "min": "20",
      "max": "100",
      "average": "40"
    },
    "extras": {
      "min": "150",
      "max": "300",
      "average": "225"
    }
  },
  "hints": [
    {
      "text": "Beaucoup d'ammendes !"
    },
    {
      "text": "Les anglais ivres sont violents surtout en soir de match."
    },
    {
      "text": "Ne pas trop manquer les cours."
    },
    {
      "text": "N'hésitez pas à voyager à Liverpool et Manchester."
    }
  ],
  "comments": [
    {
      "text": "Destination incroyable avec un campus de malade, des cours excellents, je recommande à 200%"
    },
    {
      "text": "On y apprend à devenir autonome !"
    }
  ]
}

=== Mr-Monster-0248/noMayhemTravel/public/country/cape.json
{
	"university": "Cape Peninsula University of Technology",
	"link_website": "https://www.cput.ac.za/homepage",
	"country": {
		"name": "South Africa",
		"flag_url": "...",
		"currency": "Rand -> 1 € = 15.55 ZAR"
	},
	"admission": {
		"gpa": {
			"min": "0.93",
			"max": "3.5",
			"average": "1.7"
		},

		"mark": {
			"min": "11",
			"max": "14",
			"average": "12.5"
		},

		"toeic": {
			"min": "550",
			"max": "815",
			"average": "685"
		}
	},
	"prices": {
		"plane": {
			"min": "500",
			"max": "1500",
			"average": "1000"
		},
		"food": {
			"min": "100",
			"max": "400",
			"average": "250"
		},
		"rent": {
			"min": "500",
			"max": "1000",
			"average": "750"
		},
		"trains and bus": {
			"min": "50",
			"max": "150",
			"average": "100"
		},
		"transport": {
			"min": "20",
			"max": "60",
			"average": "40"
		},
		"extras": {
			"min": "150",
			"max": "500",
			"average": "300"
		}
	},
	"hints": [
		{
			"text": "Traverser le trottoir quand c'est pas notre tour est passible de 50 euros d'ammende"
		},
		{
			"text": "Toujours donner des tips !"
		},
		{
			"text": "Prendre un bon adaptateur qui ne soit passif."
		},
		{
			"text": "Il vaut mieux payer en espèces et non pas en en carte, à cause des taxes."
		},
		{
			"text": "Faire les courses à organiser des repas à plusieurs pour éviter de payer trop cher."
		}

	],
	"comments": [{
			"text": "Attention le sixième semestre en France sera rude car on repasse sur des horraires de 8h à 18h."

		},
		{
			"text": "Tous les professeurs Tous les profs sont très compétents, beaucoup de chose à faire dans Montréal et autour."
		}
	]
}
